In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
a = 3
b = 4.5
c = "Hello"

print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>


In [3]:
print(3 + 4)
print('3' + '4')

7
34


In [4]:
# 아래 줄은 오류가 납니다 (의도된 것입니다)
print(3 + '4')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [5]:
year = '2020'
print(int(year) + 1)

2021


In [6]:
a = 3
b = 4.5
print(a, '+', b, '=', a + b)

3 + 4.5 = 7.5


In [7]:
a = [10, 20, 5]

print(a[0])
print(a[1])
print(len(a))
print(type(a))

10
20
3
<class 'list'>


In [8]:
print(a + a)

[10, 20, 5, 10, 20, 5]


In [9]:
a = [10, 20, 5]
b = a

a[0] = 100

print('a =', a)
print('b =', b)

a = [100, 20, 5]
b = [100, 20, 5]


In [10]:
a = [10, 20, 5]
b = a[:]          # 복사본을 만든다

a[0] = 3

print('a =', a)
print('b =', b)

a = [3, 20, 5]
b = [10, 20, 5]


---
## Slicing — `[start:stop:step]`

리스트의 일부만 잘라내는 방법입니다. 세 자리로 되어 있고, 각각 생략할 수 있습니다.

```
a[start : stop : step]
     │      │      └─ 몇 칸씩 건너뛸지 (기본값 1)
     │      └─ 어디까지  ※ 이 위치는 포함되지 않습니다
     └─ 어디부터 (기본값 0)
```

**`stop` 위치는 포함되지 않는다**는 점을 꼭 기억하세요.
`a[2:5]` 는 `5 - 2 = 3` 개가 나옵니다.

In [11]:
a = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
#     0   1   2   3   4   5   6   7   8   9      <- 앞에서부터 번호
#   -10  -9  -8  -7  -6  -5  -4  -3  -2  -1      <- 뒤에서부터 번호

print(a[2:5])
print(a[:3])
print(a[7:])

[12, 13, 14]
[10, 11, 12]
[17, 18, 19]


In [12]:
print(a[::2])      # 두 칸씩
print(a[1::3])     # 1번부터 세 칸씩
print(a[-3:])      # 마지막 3개
print(a[::-1])     # 거꾸로

[10, 12, 14, 16, 18]
[11, 14, 17]
[17, 18, 19]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


In [14]:
for i in range(1, 6):
    print(i)

1
2
3
4
5


In [15]:
a = [10, 20, 5]

for i in a:
    print(i)

10
20
5


In [16]:
print(20 >= 6)
print(5 >= 6)

True
False


In [17]:
for i in a:
    if i == 20:
        print(i, '-> 20 입니다')
    elif i >= 6:
        print(i, '-> 6 이상입니다')
    else:
        print(i, '-> 6 보다 작습니다')

10 -> 6 이상입니다
20 -> 20 입니다
5 -> 6 보다 작습니다


---
## NumPy

`numpy` 는 **숫자 계산을 위한 패키지** 
행렬과 벡터 계산을 빠르게 처리


In [18]:
L = [1, 2, 3]            # list
A = np.array([1, 2, 3])  # numpy array

print(L * 2)
print(A * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [19]:
print(L + L)
print(A + A)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [20]:
print([x * 2 for x in L])   # list 로 하려면 이렇게

[2, 4, 6]


In [21]:
x = np.arange(10)
print(x)

print('mean =', np.mean(x))
print('sum  =', np.sum(x))
print('std  =', np.std(x))

[0 1 2 3 4 5 6 7 8 9]
mean = 4.5
sum  = 45
std  = 2.8722813232690143


In [22]:
A = np.array([[1, 2],
              [3, 4]])
print(A)
print(A.shape)     # (행, 열)

[[1 2]
 [3 4]]
(2, 2)


In [23]:
B = np.array([[5, 6],
              [7, 8]])

print(A * B)

[[ 5 12]
 [21 32]]


In [24]:
print(A @ B)

[[19 22]
 [43 50]]


In [26]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[2, 3],
              [4, 5],
              [6, 7]])

print(A.shape, B.shape)

C = A @ B
print(C)
print(C.shape)

(2, 3) (3, 2)
[[28 34]
 [64 79]]
(2, 2)


In [27]:
x = np.arange(10)
N = len(x)

print(np.ones(N))
print(np.ones(N) @ x / N)
print(np.mean(x))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
4.5
4.5


In [28]:
a = np.arange(0, 5, 0.5)
print(a)
print(type(a))

b = np.reshape(a, [5, 2])
print(b)
print(b.shape)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
<class 'numpy.ndarray'>
[[0.  0.5]
 [1.  1.5]
 [2.  2.5]
 [3.  3.5]
 [4.  4.5]]
(5, 2)


In [29]:
print(np.mean(b, axis=0), np.mean(b, axis=0).shape)
print(np.mean(b, axis=1), np.mean(b, axis=1).shape)

[2.  2.5] (2,)
[0.25 1.25 2.25 3.25 4.25] (5,)


In [30]:
temp = np.array([28, 31, 35, 29, 33])

print(temp > 30)
print(temp[temp > 30])
print((temp > 30).sum())    # 30도를 넘은 날 수

[False  True  True False  True]
[31 35 33]
3


In [31]:
c = np.where(b <= 3, 0, b)
print(c)

[[0.  0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  3.5]
 [4.  4.5]]


In [32]:
e = b * 2
e[[0, 1], [1, 1]] = np.nan
print(e)

print(np.mean(e, axis=1))
print(np.nanmean(e, axis=1))

[[ 0. nan]
 [ 2. nan]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]]
[nan nan 4.5 6.5 8.5]
[0.  2.  4.5 6.5 8.5]
