Python and Numpy 

In [1]:
# import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 

Python Data Type: int, float, string, boolean 

In [2]:
print ("Hello world!")

Hello world!


In [3]:
a = 3 

In [4]:
print ("The value of a is:", a)

The value of a is: 3


In [5]:
print (type(a))

<class 'int'>


In [6]:
b = 4.5 

In [7]:
print (type(b))

<class 'float'>


In [8]:
print (a, '+', b, '=', a + b)

3 + 4.5 = 7.5


In [9]:
print(a+b)

7.5


In [10]:
c = "Hello"

In [11]:
print (c)

Hello


In [12]:
type(c)

str

In [13]:
a = [10, 20, 5]

In [14]:
print(a[1])

20


In [15]:
print(len(a))

3


In [16]:
print (a+a)

[10, 20, 5, 10, 20, 5]


In [17]:
b = a 

In [18]:
print(b)

[10, 20, 5]


In [19]:
a[0] = 100
print(a)

[100, 20, 5]


In [20]:
print(b)

[100, 20, 5]


In [21]:
b[0]=1
print(a)
print(b)

[1, 20, 5]
[1, 20, 5]


In [22]:
b=a[:]

In [23]:
a[0]=3 

In [24]:
print (a)
print(b)

[3, 20, 5]
[1, 20, 5]


In [25]:
##### Loop, if #####
# for i in [1, 2, 3, 4, 5]:
for i in range(1,6):
    print(i)
print("\n")

for i in a:
    print(i)
print("\n")


1
2
3
4
5


3
20
5




In [26]:

for i in a:
    if i==2:
        print(i)
    elif i>=6:
        print(i)
    else:
        print('missing')


missing
20
missing


In [27]:
x = np.arange(10)                               

In [28]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
N = len(x)
N

10

In [30]:
np.ones(N)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.ones(N)@x/N 

np.float64(4.5)

In [32]:
x/N

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [33]:
np.mean(x)

np.float64(4.5)

In [34]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
B = np.array([[2,3],[4,5],[6,7]])
B

array([[2, 3],
       [4, 5],
       [6, 7]])

In [36]:
C = A@B 
C

array([[28, 34],
       [64, 79]])

In [37]:
a=np.arange(0, 5, 0.5)
print(a)
print(type(a))

b=np.reshape(a,[5,2])
print(b)
print(b.shape)

c=np.where(b<=3, 0, b)
print(c)


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
<class 'numpy.ndarray'>
[[0.  0.5]
 [1.  1.5]
 [2.  2.5]
 [3.  3.5]
 [4.  4.5]]
(5, 2)
[[0.  0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  3.5]
 [4.  4.5]]


In [38]:

d=np.mean(b, axis=1)
print(d)
print(d.shape)



[0.25 1.25 2.25 3.25 4.25]
(5,)


In [39]:
e=b*2
print(e)




[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [40]:
e[[0,1],[1,1]] = np.nan
print(e)
print(np.nanmean(e, axis=1))
print(np.mean(e, axis=1))

[[ 0. nan]
 [ 2. nan]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]]
[0.  2.  4.5 6.5 8.5]
[nan nan 4.5 6.5 8.5]
