Python and Numpy 

In [85]:
# import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 

Python Data Type: int, float, string, boolean 

In [86]:
print ("Hello world!")

Hello world!


In [87]:
a = 3 

In [88]:
print ("The value of a is:", a)

The value of a is: 3


In [89]:
print (type(a))

<class 'int'>


In [90]:
b = 4.5 

In [91]:
print (type(b))

<class 'float'>


In [92]:
print (a, '+', b, '=', a + b)

3 + 4.5 = 7.5


In [93]:
print(a+b)

7.5


In [94]:
c = "Hello"

In [95]:
print (c)

Hello


In [96]:
type(c)

str

In [97]:
a = [10, 20, 5]

In [98]:
print(a[1])

20


In [99]:
print(len(a))

3


In [100]:
print (a+a)

[10, 20, 5, 10, 20, 5]


In [101]:
b = a 

In [102]:
print(b)

[10, 20, 5]


In [103]:
a[0] = 100
print(a)

[100, 20, 5]


In [104]:
print(b)

[100, 20, 5]


In [105]:
b[0]=1
print(a)
print(b)

[1, 20, 5]
[1, 20, 5]


In [106]:
b=a[:]

In [107]:
a[0]=3 

In [108]:
print (a)
print(b)

[3, 20, 5]
[1, 20, 5]


In [109]:
x = np.arange(10)                               

In [110]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
N = len(x)
N

10

In [112]:
np.ones(N)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [113]:
np.ones(N)@x/N 

np.float64(4.5)

In [114]:
x/N

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [115]:
np.mean(x)

np.float64(4.5)

In [116]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
B = np.array([[2,3],[4,5],[6,7]])
B

array([[2, 3],
       [4, 5],
       [6, 7]])

In [118]:
C = A@B 
C

array([[28, 34],
       [64, 79]])